### PR TITLE
Ollie ORM added to test set

### LINKED ISSUE #8: Fix broken schema images for README
At the moment both UML schemas (for simple and complex trials) at README are broken.
screen shot 2015-06-17 at 10 37 34

### PR DESCRIPTION
**Pull request by trevjonez**
Added Michael's newer and recommended library [Ollie](https://github.com/pardom/Ollie) to the test set.

I also fixed [Issue #8](https://github.com/Raizlabs/AndroidDatabaseLibraryComparison/issues/8)

Some of the Gradle plugins used have been updated. It should be noted that you can not use Gradle version 2.5 or higher to build the project. I think this is due to the griddle plugin though I am not certain.

Tests were ran on my nexus 9 tablet.

### CODE REVIEW

**Comment by PerfectCarl** [comment]
It fixes https://github.com/pardom/Ollie/issues/60 too! 

Well done.

**Comment by PerfectCarl** [comment]
Anyone interested in the preliminary results can view them there: 

### Simple

simple

### Complex

results

**Comment by trevjonez** [comment]
@Raizlabs any thing you want done in order to merge this?

**Comment by octohub** [comment]
@trevjonez Sorry for getting back so late! I am watching this now and will be more on top of it.

Looks good. Merging.

**Pull request merged**
